[project]
name = "waveshare-esp32c6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "circup>=2.3.0",
    "esptool>=5.1.0",
]
